export const blogNodes = [
  {
    type: { resolvedName: 'Blog1' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Blog1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog2' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Blog2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog3' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Blog3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog4' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Blog4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog5' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Blog5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
