export const freeBlogNodes = [
  {
    type: { resolvedName: 'Blog1' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog2' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
          },
        },
      ],
    },
    displayName: 'Blog2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const blogNodes = [
  ...freeBlogNodes,
  {
    type: { resolvedName: 'Blog3' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog4' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog5' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog6' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      featuredPostCta: '1-2 words',
      postCta: '1-2 words',
      categories: [
        { id: 1, name: '', href: '#' },
        { id: 2, name: '', href: '#' },
        { id: 3, name: '', href: '#' },
        { id: 4, name: '', href: '#' },
      ],
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
          },
        },
      ],
    },
    displayName: 'Blog6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog7' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      featuredPostCta: '1-2 words',
      postCta: '1-2 words',
      categories: [
        { id: 1, name: '', href: '#' },
        { id: 2, name: '', href: '#' },
        { id: 3, name: '', href: '#' },
        { id: 4, name: '', href: '#' },
      ],
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog7',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog8' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      categories: [
        { id: 1, name: '', href: '#' },
        { id: 2, name: '', href: '#' },
        { id: 3, name: '', href: '#' },
        { id: 4, name: '', href: '#' },
      ],
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog8',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog9' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      featuredBlogPostsHeading: '2-5 words',
      featuredPostCta: '1-2 words',
      latestPostCta: '1-2 words',
      latestBlogPostsHeading: '2-5 words',
      featuredPosts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
      latestPosts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog9',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Blog10' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      cta: '1-2 words',
      categories: [
        { id: 1, name: '', href: '#' },
        { id: 2, name: '', href: '#' },
        { id: 3, name: '', href: '#' },
        { id: 4, name: '', href: '#' },
      ],
      posts: [
        {
          id: 1,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 2,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 3,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
        {
          id: 4,
          category: '1-2 words',
          title: 'Maximum 7 words',
          description: 'Minimum 1-2 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
          metadata: {
            author: '',
            authorImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
            datetime: '2023-05-01',
            date: 'May 1, 2023',
            readingTime: '5 min read',
          },
        },
      ],
    },
    displayName: 'Blog10',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
