export const contactNodes = [
  {
    type: { resolvedName: 'Contact1' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1 sentence',
      cta: 'ACTION: 1-2 words',
    },
    displayName: 'Contact1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const freeContactNodes = [
  ...contactNodes,
  {
    type: { resolvedName: 'Contact2' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1 sentence',
      email: 'ACTION: insert email',
      phone: 'ACTION: insert phone number',
      address: 'ACTION: insert address',
      cta: 'ACTION: 1-2 words',
    },
    displayName: 'Contact2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact3' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1 sentence',
      cta: 'ACTION: 1-2 words',
    },
    displayName: 'Contact3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact4' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1 sentence',
      cta: 'ACTION: 1-2 words',
      email: 'ACTION: insert email',
      emailDescription: 'ACTION: 1 sentence',
      phone: 'ACTION: insert phone number',
      phoneDescription: 'ACTION: 1 sentence',
      addressCta: 'ACTION: 1-2 words',
      addressDescription: 'ACTION: 1 sentence',
    },
    displayName: 'Contact4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact5' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1 sentence',
      cta: 'ACTION: 1-2 words',
      email: 'ACTION: insert email',
      emailDescription: 'ACTION: 1-2 sentences',
      phone: 'ACTION: insert phone number',
      phoneDescription: 'ACTION: 1-2 sentences',
      address: 'ACTION: insert address',
      addressDescription: 'ACTION: 1-2 sentences',
    },
    displayName: 'Contact5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact6' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1 sentence',
      cta: 'ACTION: 1-2 words',
      firstReason: 'ACTION: reason of contact. 1-2 words',
      secondReason: 'ACTION: reason of contact. 1-2 words',
      thirdReason: 'ACTION: reason of contact. 1-2 words',
    },
    displayName: 'Contact6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
