export const contactNodes = [
  {
    type: { resolvedName: 'Contact1' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1 sentence',
      cta: '1-2 words',
    },
    displayName: 'Contact1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const freeContactNodes = [
  ...contactNodes,
  {
    type: { resolvedName: 'Contact2' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1 sentence',
      email: '',
      phone: '',
      address: '',
      cta: '1-2 words',
    },
    displayName: 'Contact2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact3' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1 sentence',
      cta: '1-2 words',
    },
    displayName: 'Contact3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact4' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1 sentence',
      cta: '1-2 words',
      email: '',
      emailDescription: '1 sentence',
      phone: '',
      phoneDescription: '1 sentence',
      addressCta: '1-2 words',
      addressDescription: '1 sentence',
    },
    displayName: 'Contact4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact5' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1 sentence',
      cta: '1-2 words',
      email: '',
      emailDescription: '1-2 sentences',
      phone: '',
      phoneDescription: '1-2 sentences',
      address: '',
      addressDescription: '1-2 sentences',
    },
    displayName: 'Contact5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Contact6' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1 sentence',
      cta: '1-2 words',
      firstReason: 'reason of contact. 1-2 words',
      secondReason: 'reason of contact. 1-2 words',
      thirdReason: 'reason of contact. 1-2 words',
    },
    displayName: 'Contact6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
