export const faqNodes = [
  {
    type: { resolvedName: 'FAQ1' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'FAQ1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'FAQ2' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'FAQ2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'FAQ3' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'FAQ3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'FAQ4' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'FAQ4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'FAQ5' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'FAQ5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
