export const freeFeatureNodes = [
  {
    type: { resolvedName: 'Feature1' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature2' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature3' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 2,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 3,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
      ],
    },
    displayName: 'Feature3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature4' },
    isCanvas: false,
    props: {
      heading: 'Maximum 7 words',
      cta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
        },
        {
          id: 2,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
        },
        {
          id: 3,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
        },
      ],
    },
    displayName: 'Feature4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature5' },
    isCanvas: false,
    props: {
      heading: 'Maximum 7 words',
      cta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 2,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 3,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
      ],
    },
    displayName: 'Feature5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature6' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const featureNodes = [
  ...freeFeatureNodes,
  {
    type: { resolvedName: 'Feature7' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature7',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature8' },
    isCanvas: false,
    props: {
      cta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 2,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 3,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 4,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
      ],
    },
    displayName: 'Feature8',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature9' },
    isCanvas: false,
    props: {
      featureCta: '1-2 words',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 2,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 3,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 4,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
      ],
    },
    displayName: 'Feature9',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature10' },
    isCanvas: false,
    props: {
      tagline: '1-2 words',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      featureOneHeading: '1-2 words',
      featureOneDescription: '1-2 sentences',
      featureTwoHeading: '1-2 words',
      featureTwoDescription: '1-2 sentences',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature10',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature11' },
    isCanvas: false,
    props: {
      tagline: '1-2 words',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      featureOneHeading: '1-2 words',
      featureOneDescription: '1-2 sentences',
      featureTwoHeading: '1-2 words',
      featureTwoDescription: '1-2 sentences',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature11',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature12' },
    isCanvas: false,
    props: {
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      features: [
        {
          id: 1,
          text: 'REPLACE with 1-2 sentences',
        },
        {
          id: 2,
          text: 'REPLACE with 1-2 sentences',
        },
        {
          id: 3,
          text: 'REPLACE with 1-2 sentences',
        },
      ],
    },
    displayName: 'Feature12',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature13' },
    isCanvas: false,
    props: {
      tagline: '1-2 words',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
      features: [
        {
          id: 1,
          text: 'REPLACE with 1-2 sentences',
        },
        {
          id: 2,
          text: 'REPLACE with 1-2 sentences',
        },
        {
          id: 3,
          text: 'REPLACE with 1-2 sentences',
        },
      ],
    },
    displayName: 'Feature13',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature14' },
    isCanvas: false,
    props: {
      tagline: '1-2 words',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
      features: [
        {
          id: 1,
          text: 'REPLACE with 1-2 sentences',
        },
        {
          id: 2,
          text: 'REPLACE with 1-2 sentences',
        },
        {
          id: 3,
          text: 'REPLACE with 1-2 sentences',
        },
      ],
    },
    displayName: 'Feature14',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature15' },
    isCanvas: false,
    props: {
      cta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 2,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 3,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 4,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
      ],
    },
    displayName: 'Feature15',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature16' },
    isCanvas: false,
    props: {
      cta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 2,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
        {
          id: 3,
          name: 'REPLACE with 3-5 words',
          description: 'REPLACE with 1-2 sentences',
          href: '#',
        },
      ],
    },
    displayName: 'Feature16',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature17' },
    isCanvas: false,
    props: {
      tagline: '1-2 words',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature17',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature18' },
    isCanvas: false,
    props: {
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences',
    },
    displayName: 'Feature18',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
