export const freeFeatureNodes = [
  {
    type: { resolvedName: 'Feature1' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature2' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature3' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 2,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 3,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
      ],
    },
    displayName: 'Feature3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature4' },
    isCanvas: false,
    props: {
      heading: 'Maximum 7 words',
      cta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
        },
        {
          id: 2,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
        },
        {
          id: 3,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
        },
      ],
    },
    displayName: 'Feature4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature5' },
    isCanvas: false,
    props: {
      heading: 'Maximum 7 words',
      cta: '1-2 words',
      features: [
        {
          id: 1,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 2,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
        {
          id: 3,
          name: 'Minimum 8 words',
          description: 'Minimum 2-3 sentences',
          href: '#',
          imgSrc: 'https://dummyimage.com/1280x800/d4d4d4/171717',
          alt: 'Image',
        },
      ],
    },
    displayName: 'Feature5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Feature6' },
    isCanvas: false,
    props: {
      tagline: '1-5 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 2-3 sentences about the product or service',
      primaryCta: '1-2 words',
      secondaryCta: '1-2 words',
    },
    displayName: 'Feature6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const featureNodes = [...freeFeatureNodes];
