export const freeFooterNodes = [
  {
    type: { resolvedName: 'Footer1' },
    isCanvas: false,
    props: {
      newsletterSignUpFormHeading: '',
      newsletterSignUpCTA: '',
      newsletterDisclaimerPart1: '',
      newsletterDisclaimerPrivatePolicy: 'Privacy Policy',
      newsletterDisclaimerPart2: '',
      linksLabelOne: '',
      linksLabelTwo: '',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        categoryTwo: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Footer2' },
    isCanvas: false,
    props: {
      addressLabel: 'Address',
      address: '',
      contactLabel: 'Contact',
      phoneNumber: '',
      emailAddress: '',
      linksLabelOne: '',
      linksLabelTwo: '',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        categoryTwo: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const footerNodes = [
  ...freeFooterNodes,
  {
    type: { resolvedName: 'Footer3' },
    isCanvas: false,
    props: {
      newsletterCategoryLabel: '1 word',
      newsletterSignUpSubtitle: '1-2 sentences',
      newsletterSignUpCTA: '',
      newsletterDisclaimerPart1: '',
      newsletterDisclaimerPrivatePolicy: 'Privacy Policy',
      newsletterDisclaimerPart2: '',
      linksLabelOne: '',
      linksLabelTwo: '',
      linksLabelThree: '',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        categoryTwo: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        categoryThree: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Footer4' },
    isCanvas: false,
    props: {
      newsletterHeading: '1 sentence',
      newsletterSignUpSubtitle: '1-2 sentences',
      newsletterSignUpCTA: '',
      newsletterDisclaimerPart1: '',
      newsletterDisclaimerPrivatePolicy: 'Privacy Policy',
      newsletterDisclaimerPart2: '',
      linksLabelOne: '',
      linksLabelTwo: '',
      linksLabelThree: '',
      linksLabelFour: '',
      socialLinksLabel: 'Socials',
      legalLinksLabel: 'Legal',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        categoryTwo: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        categoryThree: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        categoryFour: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        social: [
          { name: 'YouTube', href: '#' },
          { name: 'GitHub', href: '#' },
          { name: 'LinkedIn', href: '#' },
          { name: 'Facebook', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Footer5' },
    isCanvas: false,
    props: {
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        company: [
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
          { name: '', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
