export const freeFooterNodes = [
  {
    type: { resolvedName: 'Footer1' },
    isCanvas: false,
    props: {
      newsletterSignUpFormHeading: 'ACTION: 1 sentence',
      newsletterSignUpCTA: 'ACTION: 1-2 words',
      newsletterDisclaimerPart1: 'By subscribing you agree to with our ',
      newsletterDisclaimerPrivatePolicy: 'Privacy Policy',
      newsletterDisclaimerPart2:
        ' and provide consent to receive updates from our company.',
      linksLabelOne: 'ACTION: 1 word for categoryOne',
      linksLabelTwo: 'ACTION: 1 word for categoryTwo',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        categoryTwo: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Footer2' },
    isCanvas: false,
    props: {
      addressLabel: 'Address',
      address: 'ACTION: insert address',
      contactLabel: 'Contact',
      phoneNumber: 'ACTION: insert phone number',
      emailAddress: 'ACTION: insert email address',
      linksLabelOne: 'ACTION: 1 word for categoryOne',
      linksLabelTwo: 'ACTION: 1 word for categoryTwo',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        categoryTwo: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const footerNodes = [
  ...freeFooterNodes,
  {
    type: { resolvedName: 'Footer3' },
    isCanvas: false,
    props: {
      newsletterCategoryLabel: 'ACTION: 1 word',
      newsletterSignUpSubtitle: 'ACTION: 1-2 sentences',
      newsletterSignUpCTA: 'ACTION: 1-2 words',
      newsletterDisclaimerPart1: 'By subscribing you agree to with our ',
      newsletterDisclaimerPrivatePolicy: 'Privacy Policy',
      newsletterDisclaimerPart2:
        ' and provide consent to receive updates from our company.',
      linksLabelOne: 'ACTION: 1 word for categoryOne',
      linksLabelTwo: 'ACTION: 1 word for categoryTwo',
      linksLabelThree: 'ACTION: 1 word for categoryThree',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        categoryTwo: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        categoryThree: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Footer4' },
    isCanvas: false,
    props: {
      newsletterHeading: '1 sentence',
      newsletterSignUpSubtitle: 'ACTION: 1-2 sentences',
      newsletterSignUpCTA: 'ACTION: 1-2 words',
      newsletterDisclaimerPart1: 'By subscribing you agree to with our ',
      newsletterDisclaimerPrivatePolicy: 'Privacy Policy',
      newsletterDisclaimerPart2:
        ' and provide consent to receive updates from our company.',
      linksLabelOne: 'ACTION: 1 word for categoryOne',
      linksLabelTwo: 'ACTION: 1 word for categoryTwo',
      linksLabelThree: 'ACTION: 1 word for categoryThree',
      linksLabelFour: 'ACTION: 1 word for categoryFour',
      socialLinksLabel: 'Socials',
      legalLinksLabel: 'Legal',
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        categoryOne: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        categoryTwo: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        categoryThree: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        categoryFour: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        social: [
          { name: 'YouTube', href: '#' },
          { name: 'GitHub', href: '#' },
          { name: 'LinkedIn', href: '#' },
          { name: 'Facebook', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Footer5' },
    isCanvas: false,
    props: {
      legal: '&copy; 2020 Your Company, Inc. All rights reserved.',
      navigation: {
        company: [
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
          { name: 'ACTION: 1 word', href: '#' },
        ],
        legal: [
          { name: 'Privacy Policy', href: '#' },
          { name: 'Terms of Service', href: '#' },
          { name: 'Cookies', href: '#' },
        ],
      },
    },
    displayName: 'Footer5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
