export const freeGalleryNodes = [
  {
    type: { resolvedName: 'Gallery1' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1-2 sentences',
    },
    displayName: 'Gallery1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery2' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1-2 sentences',
    },
    displayName: 'Gallery2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const galleryNodes = [
  ...freeGalleryNodes,
  {
    type: { resolvedName: 'Gallery3' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1-2 sentences',
    },
    displayName: 'Gallery3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery4' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1-2 sentences',
    },
    displayName: 'Gallery4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery5' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1-2 sentences',
    },
    displayName: 'Gallery5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery6' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 1-2 sentences',
    },
    displayName: 'Gallery6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
