export const galleryNodes = [
  {
    type: { resolvedName: 'Gallery1' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Gallery1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery2' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Gallery2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery3' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Gallery3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery4' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Gallery4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Gallery5' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Gallery5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
