export const headingNodes = [
  {
    type: { resolvedName: 'Heading1' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Heading1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading2' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Heading2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading3' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Heading3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading4' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Heading4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading5' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Heading5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
