export const freeHeadingNodes = [
  {
    type: { resolvedName: 'Heading1' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-3 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Heading1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading2' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-3 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Heading2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const headingNodes = [
  ...freeHeadingNodes,
  {
    type: { resolvedName: 'Heading3' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Heading3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading4' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-3 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description:
        'Minimum 2-3 sentences. This is a description of the newsletter.',
      primaryCta: 'ACTION: 1-2 words',
      newsletterDisclaimerPart1: '',
      newsletterDisclaimerPrivatePolicy: 'Privacy Policy',
      newsletterDisclaimerPart2: '',
    },
    displayName: 'Heading4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading5' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
    },
    displayName: 'Heading5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading6' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
    },
    displayName: 'Heading6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Heading7' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-3 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Heading7',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
