export const freeHeroNodes = [
  {
    type: { resolvedName: 'Hero1' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero2' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const heroNodes = [
  ...freeHeroNodes,
  {
    type: { resolvedName: 'Hero3' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero4' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero5' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero6' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero7' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero7',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero8' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero8',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero9' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero9',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero10' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero10',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero11' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero11',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero12' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      secondaryCta: 'ACTION: 1-2 words',
    },
    displayName: 'Hero12',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero13' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      primaryCta: 'ACTION: 1-2 words',
      items: [
        {
          id: 1,
          name: 'ACTION: 2-3 words',
          description: 'ACTION: 1-2 sentences',
        },
        {
          id: 2,
          name: 'ACTION: 2-3 words',
          description: 'ACTION: 1-2 sentences',
        },
        {
          id: 3,
          name: 'ACTION: 2-3 words',
          description: 'ACTION: 1-2 sentences',
        },
      ],
    },
    displayName: 'Hero13',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Hero14' },
    isCanvas: false,
    props: {
      tagline: 'ACTION: 1-5 words. Separate from the heading',
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences about the product or service',
      primaryCta: 'ACTION: 1-2 words',
      items: [
        {
          id: 1,
          name: 'ACTION: 2-3 words',
          description: 'ACTION: 1-2 sentences',
        },
        {
          id: 2,
          name: 'ACTION: 2-3 words',
          description: 'ACTION: 1-2 sentences',
        },
        {
          id: 3,
          name: 'ACTION: 2-3 words',
          description: 'ACTION: 1-2 sentences',
        },
      ],
    },
    displayName: 'Hero14',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
