export const logosNodes = [
  {
    type: { resolvedName: 'Logos1' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Logos1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Logos2' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Logos2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Logos3' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Logos3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Logos4' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      btn: '',
    },
    displayName: 'Logos4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Logos5' },
    isCanvas: false,
    props: {
      tagline: '',
      title: '',
      subtitle: '',
      primaryBtn: '',
      secondaryBtn: '',
    },
    displayName: 'Logos5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
