export const freeTeamNodes = [
  {
    type: { resolvedName: 'Team1' },
    isCanvas: false,
    props: {
      tagline: '1-3 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1-2 sentences',
      secondHeading: 'Maximum 7 words',
      secondDescription: 'Minimum 1-2 sentences',
      cta: '1-2 words',
      team: [
        {
          id: 1,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 2,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 3,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 4,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 5,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 6,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
      ],
    },
    displayName: 'Team1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Team2' },
    isCanvas: false,
    props: {
      tagline: '1-3 words. Separate from the heading',
      heading: 'Maximum 7 words',
      description: 'Minimum 1-2 sentences',
      secondHeading: 'Maximum 7 words',
      secondDescription: 'Minimum 1-2 sentences',
      cta: '1-2 words',
      team: [
        {
          id: 1,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 2,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 3,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 4,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 5,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
        {
          id: 6,
          name: '',
          imageSrc: 'https://dummyimage.com/150x150/d4d4d4/171717',
          title: '',
          description: '',
        },
      ],
    },
    displayName: 'Team2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const teamNodes = [...freeTeamNodes];
