export const freeTestimonialNodes = [
  {
    type: { resolvedName: 'Testimonial1' },
    isCanvas: false,
    props: {
      name: 'ACTION: Insert name',
      position: 'ACTION: Insert position',
      company: 'ACTION: Insert company name',
      testimonial: 'Minimum 2-3 sentences',
    },
    displayName: 'Testimonial1',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Testimonial2' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      testimonials: [
        {
          id: 1,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content:
            'ACTION: Insert testimonial minimum 1-2 sentences wrapped in " "',
        },
        {
          id: 2,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content:
            'ACTION: Insert testimonial minimum 1-2 sentences wrapped in " "',
        },
        {
          id: 3,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content:
            'ACTION: Insert testimonial minimum 1-2 sentences wrapped in " "',
        },
      ],
    },
    displayName: 'Testimonial2',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];

export const testimonialNodes = [
  ...freeTestimonialNodes,
  {
    type: { resolvedName: 'Testimonial3' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      testimonials: [
        {
          id: 1,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content:
            'ACTION: Insert testimonial minimum 1-2 sentences wrapped in " "',
        },
        {
          id: 2,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content:
            'ACTION: Insert testimonial minimum 1-2 sentences wrapped in " "',
        },
        {
          id: 3,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content:
            'ACTION: Insert testimonial minimum 1-2 sentences wrapped in " "',
        },
      ],
    },
    displayName: 'Testimonial3',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Testimonial4' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      firstColumn: [
        {
          id: 1,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 2,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
      ],
      secondColumn: [
        {
          id: 1,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 2,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
      ],
      thirdColumn: [
        {
          id: 1,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 2,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
      ],
    },
    displayName: 'Testimonial4',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Testimonial5' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      testimonials: [
        {
          id: 1,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 2,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 3,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 4,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 5,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          logoImg: 'https://img.logoipsum.com/297.svg',
          profileImg: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
      ],
    },
    displayName: 'Testimonial5',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  {
    type: { resolvedName: 'Testimonial6' },
    isCanvas: false,
    props: {
      heading: 'ACTION: Maximum 7 words',
      description: 'ACTION: Minimum 2-3 sentences',
      testimonials: [
        {
          id: 1,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 2,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 3,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 4,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 5,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
        {
          id: 6,
          name: 'ACTION: Insert name',
          position: 'ACTION: Insert position',
          company: 'ACTION: Insert company name',
          imgSrc: 'https://dummyimage.com/100x100/d4d4d4/171717',
          content: 'ACTION: Insert testimonial minimum 1-2 sentences',
        },
      ],
    },
    displayName: 'Testimonial6',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
];
